### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by ShDdu** [RingoS/nfc-parser#1]
你好，请问模型的输入数据是怎么样的呀，能否给几条数据做个示例

**Comment by ringos** [comment]
数据可以参考[Self-attentive Parser的repo](https://github.com/nikitakit/self-attentive-parser/tree/master/data)。

**Comment by ShDdu** [comment]
能不能给两条例子呀，我没有购买那个数据集，运行不了他的代码

**Comment by Nealcly** [comment]
> 能不能给两条例子呀，我没有购买那个数据集，运行不了他的代码

(TOP (S (NP (DT The) (JJ new) (NN rate)) (VP (MD will) (VP (VB be) (ADJP (JJ payable) (NP (NNP Feb.) (CD 15))))) (. .)))
